# Permalinks
permalink:           pretty

# Setup
title:               Anil Polavarapu
tagline:             
url:                 
paginate:            1
baseurl:             ""

pages_list:       
  About: '/about'
  Books: '/books'
  Archive: '/archive'  

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anil Polavarapu
  url:               
  email:             pvanil.kumar@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/AnilPolavarapu/AnilPolavarapu.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
